# Generated by Django 3.2 on 2021-04-20 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('other_information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.CharField(max_length=128)),
                ('sold', models.BooleanField(default=False)),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrycontrol.imobiliaria')),
            ],
        ),
    ]
